<?php


namespace App\Helpers\SchemaHelper;


class SchemaHelper
{
    private Schema $schema;

    public function __construct(Schema $schema)
    {
        $this->schema = $schema;
    }

    public function build($item)
    {
        return '<script type="application/ld+json">' . collect($this->schema->build($item))->toJson() . '</script><!-- Generated by Itsaco (Milad Sh) -->';
    }
}
